# Project Information
site_name: ZappiStore Security Training
site_description: Public versions of ZappiStore's employee security training courses.
site_author: ZappiStore.
site_favicon: 'assets/img/icon.png'
site_url: https://training.zappi-cypher.com

# Copyright
copyright: 'Copyright &copy; ZappiStore.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/extra.css']
extra:
  logo: 'assets/img/icon.png'
  cover: 'assets/img/cover.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'Intellection'

# Contents
pages:
  - Overview: 'index.md'
  - For Everyone: 'for_everyone/index.md'
  - For Engineers: 'for_build/index.md'

# Analytics
# google_analytics: ['UA-8759953-1', 'auto']

# Extensions
# markdown_extensions:
#   - toc(permalink=#)
#   - sane_lists:
#   - admonition:
#   - meta:
#   - pymdownx.extra:
#   - pymdownx.mark:
#   - pymdownx.tilde:
